wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.16
    start_time: 1784324419.657702
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 3
      - 15
      - 16
      - 23
      4: 3.8.16
      5: 0.14.0
      8:
      - 1
      - 3
      - 5
classes:
  desc: null
  value:
  - top
  - sid
  - bot
device:
  desc: null
  value: cpu
dt:
  desc: null
  value: 1.0e-07
feature:
  desc: null
  value: alpha
high_pass:
  desc: null
  value: 1200000
low_pass:
  desc: null
  value: 0
model_architecture:
  desc: null
  value: SVM
sig_len:
  desc: null
  value: 2048
task:
  desc: null
  value: classification
test_path:
  desc: null
  value: distance/stratified/10/10_test.json
train_path:
  desc: null
  value: distance/stratified/10/10_train.json
valid_path:
  desc: null
  value: ''
validation_method:
  desc: null
  value: holdout
